# -*- coding: utf-8 -*-
"""individual_clinical_trends_plot_mdpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsHezvCIIrBqnw3XLWlcPx1T8BR5p8fo
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os

# --- 1. Font settings (support English and avoid minus sign issues) ---
plt.rcParams['font.sans-serif'] = ['Arial']  # Standard sans-serif font for international journals
plt.rcParams['axes.unicode_minus'] = False

# --- 2. Load and preprocess data ---
file_path = 'participant_clinical_outcomes.csv'
df = pd.read_csv(file_path)

df_bbt = df[df['Assessment'] == 'BBT'].copy()
df_nhpt = df[df['Assessment'] == 'NHPT'].copy()

# Calculate the average of two trials for the left (affected) hand
for phase in ['Baseline', 'Interim', 'Final']:
    df_bbt[f'{phase}_Left_Avg'] = df_bbt[[f'{phase}_Left_1', f'{phase}_Left_2']].mean(axis=1)
    df_nhpt[f'{phase}_Left_Avg'] = df_nhpt[[f'{phase}_Left_1', f'{phase}_Left_2']].mean(axis=1)

# Define phases for plotting
phases = ['Baseline', 'Interim', 'Final']
x_labels = ['baseline', 'interim', 'final']  # X-axis labels (lowercase)

# Academic color palette and markers
colors = ['#0072B2', '#D55E00', '#009E73']
markers = ['o', 's', '^']

# --- 3. Plot journal-quality BBT individual trends (affected hand) ---
fig_bbt, ax_bbt = plt.subplots(figsize=(7, 5.5), dpi=300)

for idx, row in df_bbt.reset_index(drop=True).iterrows():
    y_values = [row[f'{p}_Left_Avg'] for p in phases]
    ax_bbt.plot(x_labels, y_values, marker=markers[idx], markersize=8, linewidth=2.5,
                label=f"Participant A00{idx + 1}", color=colors[idx])

    for i, v in enumerate(y_values):
        ax_bbt.text(i, v + 1.5, f'{v:.1f}', ha='center', va='bottom', fontsize=11, fontweight='bold', color=colors[idx])

ax_bbt.set_title('Box and Block Test (BBT) - Affected Side', fontsize=15, pad=15, fontweight='bold')
ax_bbt.set_ylabel('Average Number of Blocks', fontsize=13)

# Academic styling for BBT
ax_bbt.grid(True, linestyle='--', alpha=0.4)
ax_bbt.legend(fontsize=11, loc='best', framealpha=0.9)
ax_bbt.spines['top'].set_visible(False)
ax_bbt.spines['right'].set_visible(False)

y_min_bbt, y_max_bbt = ax_bbt.get_ylim()
ax_bbt.set_ylim(y_min_bbt - (y_max_bbt - y_min_bbt) * 0.15, y_max_bbt + (y_max_bbt - y_min_bbt) * 0.15)

plt.tight_layout()
plt.savefig('BBT_Individual_Trends.png', dpi=300, bbox_inches='tight')
plt.show()

# --- 4. Plot journal-quality NHPT individual trends (affected hand) ---
fig_nhpt, ax_nhpt = plt.subplots(figsize=(7, 5.5), dpi=300)

for idx, row in df_nhpt.reset_index(drop=True).iterrows():
    y_values = [row[f'{p}_Left_Avg'] for p in phases]
    ax_nhpt.plot(x_labels, y_values, marker=markers[idx], markersize=8, linewidth=2.5,
                 label=f"Participant A00{idx + 1}", color=colors[idx])

    for i, v in enumerate(y_values):
        ax_nhpt.text(i, v - 1.5, f'{v:.1f}', ha='center', va='top', fontsize=11, fontweight='bold', color=colors[idx])

ax_nhpt.set_title('Nine-Hole Peg Test (NHPT) - Affected Side', fontsize=15, pad=15, fontweight='bold')
ax_nhpt.set_ylabel('Average Completion Time (s)', fontsize=13)

# Academic styling for NHPT
ax_nhpt.grid(True, linestyle='--', alpha=0.4)
ax_nhpt.legend(fontsize=11, loc='best', framealpha=0.9)
ax_nhpt.spines['top'].set_visible(False)
ax_nhpt.spines['right'].set_visible(False)

y_min_nhpt, y_max_nhpt = ax_nhpt.get_ylim()
ax_nhpt.set_ylim(y_min_nhpt - (y_max_nhpt - y_min_nhpt) * 0.15, y_max_nhpt + (y_max_nhpt - y_min_nhpt) * 0.15)

plt.tight_layout()
plt.savefig('NHPT_Individual_Trends.png', dpi=300, bbox_inches='tight')
plt.show()