# -*- coding: utf-8 -*-
"""paired_hedges_g_forest_plot_mdpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16j0AFa97mMuBPotHzJEDpmWDNnX8Mqhg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- 1. Font and global settings ---
plt.rcParams['font.sans-serif'] = ['Arial']
plt.rcParams['axes.unicode_minus'] = False

# --- 2. Load and preprocess data ---
file_path = 'participant_clinical_outcomes.csv'
df = pd.read_csv(file_path)

df_bbt = df[df['Assessment'] == 'BBT'].copy()
df_nhpt = df[df['Assessment'] == 'NHPT'].copy()

for phase in ['Baseline', 'Final']:
    df_bbt[f'{phase}_Left_Avg'] = df_bbt[[f'{phase}_Left_1', f'{phase}_Left_2']].mean(axis=1)
    df_nhpt[f'{phase}_Left_Avg'] = df_nhpt[[f'{phase}_Left_1', f'{phase}_Left_2']].mean(axis=1)

# --- 3. Statistical calculation (Paired Hedges' g) ---
def calculate_hedges_g(pre_scores, post_scores, is_lower_better=False):
    pre = np.array(pre_scores)
    post = np.array(post_scores)
    N = len(pre)

    if is_lower_better:
        diffs = pre - post
    else:
        diffs = post - pre

    mean_diff = np.mean(diffs)
    sd_diff = np.std(diffs, ddof=1)

    d_z = mean_diff / sd_diff if sd_diff != 0 else 0

    if N > 1:
        j_factor = 1 - (3 / (4 * N - 5))
        g = d_z * j_factor
    else:
        g = 0
        j_factor = 0

    individual_g = (diffs / sd_diff) * j_factor if sd_diff != 0 else np.zeros(N)
    return g, individual_g

bbt_pre = df_bbt['Baseline_Left_Avg'].tolist()
bbt_post = df_bbt['Final_Left_Avg'].tolist()
nhpt_pre = df_nhpt['Baseline_Left_Avg'].tolist()
nhpt_post = df_nhpt['Final_Left_Avg'].tolist()

g_bbt, ind_g_bbt = calculate_hedges_g(bbt_pre, bbt_post, is_lower_better=False)
g_nhpt, ind_g_nhpt = calculate_hedges_g(nhpt_pre, nhpt_post, is_lower_better=True)

print(f"BBT Group Hedges' g = {g_bbt:.2f}")
print(f"NHPT Group Hedges' g = {g_nhpt:.2f}")
print(f"BBT Individual g values: {ind_g_bbt}")
print(f"NHPT Individual g values: {ind_g_nhpt}")

# --- 4. Plotting ---
fig, ax = plt.subplots(figsize=(9, 4.5), dpi=300)

y_bbt = 1
y_nhpt = 0

# Dynamically calculate the end of the horizontal lines
all_values = list(ind_g_bbt) + list(ind_g_nhpt) + [g_bbt, g_nhpt]
line_end = max(all_values) + 0.4
line_start = 0.0

# Draw vertical effect size threshold lines
for threshold in [0.2, 0.5, 0.8]:
    ax.axvline(x=threshold, color='gray', linestyle='--', linewidth=0.8, alpha=0.6, zorder=0)

# Threshold labels
ax.text(0.2, 1.75, 'Small (0.2)', color='gray', fontsize=9, fontstyle='italic', ha='center', va='bottom')
ax.text(0.5, 1.75, 'Moderate (0.5)', color='gray', fontsize=9, fontstyle='italic', ha='center', va='bottom')
ax.text(0.8, 1.75, 'Large (0.8)', color='gray', fontsize=9, fontstyle='italic', ha='center', va='bottom')

# --- Plot BBT ---
ax.plot([line_start, line_end], [y_bbt, y_bbt], color='lightgray', linestyle='-', linewidth=1.2, zorder=1)
for i, val in enumerate(ind_g_bbt):
    ax.scatter(val, y_bbt, color='black', s=40, zorder=3,
               label='Individual Standardized Change' if i == 0 else "")
    ax.text(val, y_bbt + 0.15, f'A00{i+1}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# --- Plot NHPT ---
ax.plot([line_start, line_end], [y_nhpt, y_nhpt], color='lightgray', linestyle='-', linewidth=1.2, zorder=1)

# Handle NHPT label overlap
nhpt_sorted = sorted(enumerate(ind_g_nhpt), key=lambda x: x[1])
for rank, (i, val) in enumerate(nhpt_sorted):
    ax.scatter(val, y_nhpt, color='black', s=40, zorder=3)
    if rank > 0 and abs(val - nhpt_sorted[rank-1][1]) < 0.15:
        if rank % 2 == 1:
            ax.text(val - 0.08, y_nhpt + 0.15, f'A00{i+1}', ha='right', va='bottom', fontsize=9, fontweight='bold')
        else:
            ax.text(val + 0.08, y_nhpt + 0.15, f'A00{i+1}', ha='left', va='bottom', fontsize=9, fontweight='bold')
    else:
        ax.text(val, y_nhpt + 0.15, f'A00{i+1}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# --- Plot group effect sizes (diamond markers) ---
ax.scatter(g_bbt, y_bbt, color='#D55E00', marker='D', s=140, zorder=4,
           edgecolor='white', linewidth=1.5, label="Group Effect Size (Hedges' $g$)")
ax.scatter(g_nhpt, y_nhpt, color='#D55E00', marker='D', s=140, zorder=4,
           edgecolor='white', linewidth=1.5)

# Numeric labels below the diamonds
ax.text(g_bbt, y_bbt - 0.15, f"$g$ = {g_bbt:.2f}", ha='center', va='top', fontsize=11, fontweight='bold')
ax.text(g_nhpt, y_nhpt - 0.15, f"$g$ = {g_nhpt:.2f}", ha='center', va='top', fontsize=11, fontweight='bold')

# Y-axis settings
ax.set_yticks([y_nhpt, y_bbt])
ax.set_yticklabels(['NHPT', 'BBT'], fontsize=13, fontweight='bold')
ax.set_ylim(-0.5, 2.0)

# X-axis settings
ax.set_xlabel("Hedges' $g$", fontsize=14, labelpad=10)
ax.set_xlim(0.0, max(1.8, line_end))

# Remove top and right spines
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.tick_params(axis='y', length=0)

# Legend
handles, labels = ax.get_legend_handles_labels()
by_label = dict(zip(labels, handles))
ax.legend(by_label.values(), by_label.keys(), loc='lower right',
          framealpha=1.0, edgecolor='black', fontsize=10)

plt.tight_layout()
plt.savefig('Hedges_g_ForestPlot.png', dpi=300, bbox_inches='tight', pad_inches=0.05)
plt.show()