# -*- coding: utf-8 -*-
"""Train2_posture_restriction_plot_mdpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zw79UMiax9vdgdqnt9-PzwPI2_N0N_2e
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

# --- 1. Global font and academic journal formatting ---
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial']  # Standard international journal font
plt.rcParams['axes.unicode_minus'] = False

plt.rcParams.update({
    'font.size': 12,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 12
})

# --- 2. Load and clean Game 2 data ---
file_path = 'A001_data_train2.csv'  # Updated filename
df2 = pd.read_csv(file_path)

# Convert numeric columns
df2['Total_Shots'] = pd.to_numeric(df2['Total_Shots'], errors='coerce')
df2['Score'] = pd.to_numeric(df2['Score'], errors='coerce')

# Fill missing dates (only the first row of each session has a date)
df2['Date'] = df2['Date'].ffill()

# Handle Posture_Rule: blank means Strict (restricted), 'F' means Unrestricted
df2['Posture_Rule'] = df2['Posture_Rule'].fillna('Strict').replace('F', 'Unrestricted')

# Calculate accuracy
df2['Accuracy'] = (df2['Score'] / df2['Total_Shots']) * 100

# Add a sequential order column
df2['Order'] = df2.index + 1

# --- 3. Plotting function: Methodological correction (Figure 7) ---
def plot_methodological_correction(data):
    fig, ax = plt.subplots(figsize=(8, 5), dpi=300)

    # Separate the two phases
    unrest = data[data['Posture_Rule'] == 'Unrestricted']
    rest = data[data['Posture_Rule'] == 'Strict']

    # Plot Unrestricted Posture (Compensatory phase) - Orange dashed line
    if not unrest.empty:
        ax.plot(unrest['Order'], unrest['Accuracy'], marker='o', linestyle='--',
                color='#D55E00', linewidth=2.5, markersize=7,
                label='Unrestricted Posture (Compensatory)')

    # Plot Strict Posture (True Motor Control phase) - Blue solid line
    if not rest.empty:
        ax.plot(rest['Order'], rest['Accuracy'], marker='s', linestyle='-',
                color='#0072B2', linewidth=2.5, markersize=7,
                label='Strict Posture Control (True Motor)')

    # Add vertical line separating the phases
    if not unrest.empty and not rest.empty:
        split_point = unrest['Order'].max() + 0.5
        ax.axvline(x=split_point, color='#7F7F7F', linestyle=':', linewidth=2)
        ax.text(split_point - 0.5, 10, 'Correction Applied',
                rotation=90, va='bottom', ha='right', color='#7F7F7F', fontsize=11, fontweight='bold')

    # Axis labels
    ax.set_xlabel('Cumulative Session Number', fontweight='bold', labelpad=10)
    ax.set_ylabel('Hit Rate (%)', fontweight='bold')

    # Participant label inside the plot (top-left)
    ax.text(0.02, 0.95, "Participant A001",
            transform=ax.transAxes, fontsize=13, fontweight='bold',
            va='top', ha='left', bbox=dict(facecolor='white', edgecolor='none', alpha=0.85), zorder=5)

    # Axis limits and ticks
    ax.set_ylim(-5, 105)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))

    # Remove top and right spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Grid and legend
    ax.grid(True, linestyle='--', alpha=0.4)
    ax.legend(loc='lower right', framealpha=1.0, edgecolor='black')

    plt.tight_layout()

    # Save high-resolution figure
    output_filename = 'Posture_Restriction_Impact_A001.png'
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"Successfully saved: {output_filename}")
    plt.show()

# --- 4. Execute ---
plot_methodological_correction(df2)