# -*- coding: utf-8 -*-
"""train2_shots_and_hit_rate_plot_mdpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QChbfB__38ZbI_ca_xS8AjC1_GYIfMj_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.ticker import MaxNLocator
import os

# ==========================================
# 1. Global font and academic journal formatting
# ==========================================
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial']
plt.rcParams['axes.unicode_minus'] = False

plt.rcParams.update({
    'font.size': 12,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 11
})

# ==========================================
# 2. Data loading and preprocessing function (Robust version)
# ==========================================
def load_and_clean_data(file_path):
    # Use encoding='utf-8-sig' to handle BOM characters often found in Excel-generated CSVs
    df = pd.read_csv(file_path, encoding='utf-8-sig')

    # Strip whitespace from column names
    df.columns = df.columns.str.strip()

    # Standardize column names to lowercase to handle both 'Total_Shots' and 'total_shots'
    df.columns = [c.lower() for c in df.columns]

    # Rename using the standardized lowercase mapping
    column_mapping = {
        '日期': 'date',
        'total_shots': 'total_shots',
        'score': 'score',
        'posture_rule': 'posture_rule'
    }
    df = df.rename(columns=column_mapping)

    # Convert numeric columns
    df['total_shots'] = pd.to_numeric(df['total_shots'], errors='coerce')
    df['score'] = pd.to_numeric(df['score'], errors='coerce')

    # Fill missing dates (forward fill)
    df['date'] = df['date'].ffill()

    # Handle Posture_Rule: blank means Strict, 'F' means Unrestricted
    df['posture_rule'] = df['posture_rule'].fillna('Strict').replace('F', 'Unrestricted')

    # Calculate accuracy
    df['accuracy'] = (df['score'] / df['total_shots']) * 100

    # Extract only the "Strict Posture" phase (True Motor Control)
    strict_data = df[df['posture_rule'] == 'Strict'].reset_index(drop=True)
    strict_data['Order'] = strict_data.index + 1
    return strict_data

# ==========================================
# 3. Load data and calculate global Y-axis
# ==========================================
file_names = {
    'A001': 'A001_data_train2.csv',
    'A002': 'A002_data_train2.csv',
    'A003': 'A003_data_train2.csv'
}

print("="*50)
print("Processing train2 data and generating individual plots")
print("="*50)

participants_data = {}
global_max_shots = 20

for pid, fname in file_names.items():
    if os.path.exists(fname):
        p_data = load_and_clean_data(fname)
        participants_data[pid] = p_data
        if not p_data.empty:
            global_max_shots = max(global_max_shots, p_data['total_shots'].max())
    else:
        print(f"File not found: {fname}")

MAX_SHOTS_Y = (global_max_shots // 10 + 1) * 10

# ==========================================
# 4. Plot and export 3 individual figures
# ==========================================
color_bar = '#aec7e8'
color_trend = '#1f77b4'
color_acc = '#ff7f0e'

for pid, p_data in participants_data.items():
    if p_data.empty:
        print(f"⚠️ Skipping plot: {pid} has no valid data")
        continue

    fig, ax = plt.subplots(figsize=(6, 5), dpi=300)
    x_val = p_data['Order']

    # Left Y-axis: Total Shots per Session (Bar chart)
    ax.bar(x_val, p_data['total_shots'], color=color_bar, alpha=0.8, width=0.6)

    # Left Y-axis: Shots Trend (Rolling Mean)
    trend_shots = p_data['total_shots'].rolling(window=3, min_periods=1).mean()
    ax.plot(x_val, trend_shots, color=color_trend, linestyle='--', linewidth=2.5, alpha=0.9)

    ax.set_ylabel('Total Shots', fontweight='bold')
    ax.set_ylim(0, MAX_SHOTS_Y)

    # Right Y-axis: Hit Rate (Line chart)
    ax_twin = ax.twinx()
    ax_twin.plot(x_val, p_data['accuracy'], marker='o', color=color_acc, linewidth=2.5)
    ax_twin.set_ylabel('Hit Rate (%)', color=color_acc, fontweight='bold')
    ax_twin.tick_params(axis='y', colors=color_acc)
    ax_twin.set_ylim(-5, 110)

    ax.set_xlim(x_val.min() - 0.5, x_val.max() + 0.5)
    ax.grid(True, alpha=0.3)

    ax.set_xlabel('Session Number (Strict Posture Phase)', fontweight='bold', labelpad=10)
    ax.set_xticks(x_val)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True, prune='both' if len(x_val)>20 else None))

    ax.text(0.02, 0.95, f"Participant {pid}",
            transform=ax.transAxes, fontsize=13, fontweight='bold',
            va='top', ha='left', bbox=dict(facecolor='white', edgecolor='none', alpha=0.85), zorder=5)

    ax.spines['top'].set_visible(False)
    ax_twin.spines['top'].set_visible(False)

    legend_elements = [
        mpatches.Patch(color=color_bar, alpha=0.9, label='Shots per Session'),
        plt.Line2D([0], [0], color=color_trend, linestyle='--', linewidth=2.5, label='Shots Trend'),
        plt.Line2D([0], [0], color=color_acc, marker='o', linewidth=2.5, label='Hit Rate (%)')
    ]

    ax.legend(handles=legend_elements, loc='lower center', bbox_to_anchor=(0.5, 1.05),
              ncol=3, framealpha=1.0, edgecolor='black', columnspacing=1.0)

    plt.tight_layout()
    output_filename = f'train2_total_shots_and_hit_rate_{pid}.png'
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"Successfully saved: {output_filename}")

    plt.close(fig)

print("\nAll individual plots have been exported!")