# -*- coding: utf-8 -*-
"""train4_stacking_and_area_plot_mdpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYNy4WNao3aw3nlFcEgD3Ln3xPv4TkNy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from matplotlib.ticker import MaxNLocator

# ==========================================
# 1. 期刊字體與排版全局設定
# ==========================================
plt.rcParams['font.family'] = 'Arial'
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams.update({
    'font.size': 12,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 11
})

# ==========================================
# 2. 資料處理函數
# ==========================================
def process_cleaned_data(file_path):
    df = pd.read_csv(file_path, encoding='utf-8-sig')

    # 確保數值欄位為數字
    for col in ['Total_Duration', 'Hand_Movement_Area', 'Block_Score', 'Grab_Duration']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # 按 Session_ID 分組
    session_list = []
    for sid, group in df.groupby('Session_ID'):
        group = group.reset_index(drop=True)

        # 只取 Block_Score >= 18 的有效嘗試
        valid_blocks = group[group['Block_Score'] >= 18].copy()
        avg_score = valid_blocks['Block_Score'].mean() if not valid_blocks.empty else np.nan
        avg_score_pct = (avg_score / 36.0) * 100 if pd.notnull(avg_score) else np.nan

        # 計算 CV（變異係數）
        if len(valid_blocks) > 1 and avg_score > 0:
            score_cv = (valid_blocks['Block_Score'].std() / avg_score) * 100
        else:
            score_cv = 0

        # 手部移動面積平均
        avg_area = group['Hand_Movement_Area'].mean()

        session_list.append({
            'Session_ID': sid,
            'Avg_Score_Pct': avg_score_pct,
            'Score_CV': score_cv,
            'Hand_Area': avg_area
        })

    df_sess = pd.DataFrame(session_list).sort_values('Session_ID').reset_index(drop=True)

    # 過濾極端異常值（IQR）
    Q1 = df_sess['Hand_Area'].quantile(0.25)
    Q3 = df_sess['Hand_Area'].quantile(0.75)
    IQR_value = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR_value
    upper_bound = Q3 + 1.5 * IQR_value
    df_sess.loc[(df_sess['Hand_Area'] < lower_bound) | (df_sess['Hand_Area'] > upper_bound), 'Hand_Area'] = np.nan

    df_sess['Order'] = df_sess.index + 1
    return df_sess

# ==========================================
# 3. 繪圖並匯出函數（共產出 6 張圖）
# ==========================================
def plot_individual_figures(subjects_data, hand='左'):
    subject_keys = list(subjects_data.keys())

    # 掃描 Y 軸（移動面積）的全域最大/最小值
    global_max_area = 0
    global_min_area = float('inf')
    for subj, df in subjects_data.items():
        if not df.empty:
            valid_area = df['Hand_Area'].dropna()
            if not valid_area.empty:
                global_max_area = max(global_max_area, valid_area.max())
                global_min_area = min(global_min_area, valid_area.min())

    area_padding = (global_max_area - global_min_area) * 0.15
    y_min_area = max(0, global_min_area - area_padding)
    y_max_area = global_max_area + area_padding

    # ------------------------------------------
    # 圖表 1：Stacking Accuracy 與 CV
    # ------------------------------------------
    for subj in subject_keys:
        df_sess = subjects_data[subj]
        if df_sess.empty:
            continue

        fig, ax = plt.subplots(figsize=(6, 5), dpi=300)
        x_sess = df_sess['Order'].values

        ax.plot(x_sess, df_sess['Avg_Score_Pct'], 'o-', color='#2ca02c', linewidth=2, markersize=6, label='Stacking Accuracy (%)')
        ax.set_ylabel('Stacking Accuracy (%)', color='#2ca02c', fontweight='bold')
        ax.set_ylim(40, 105)

        ax_twin = ax.twinx()
        ax_twin.bar(x_sess, df_sess['Score_CV'], color='dimgray', alpha=0.6, width=0.5, label='CV (%)')
        ax_twin.set_ylabel('CV (%)', color='dimgray', fontweight='bold')
        ax_twin.set_ylim(0, 100)

        max_order = df_sess['Order'].max()
        ax.set_xlim(0.5, max_order + 0.5)
        ax.grid(True, alpha=0.3)
        ax.set_xlabel('Session Number', fontweight='bold')
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))

        ax.text(0.02, 0.95, f"Participant {subj}",
                transform=ax.transAxes, fontsize=13, fontweight='bold',
                va='top', ha='left', bbox=dict(facecolor='white', edgecolor='none', alpha=0.85))

        lines, lbls = ax.get_legend_handles_labels()
        lines2, lbls2 = ax_twin.get_legend_handles_labels()
        ax.legend(lines + lines2, lbls + lbls2, loc='lower center',
                  bbox_to_anchor=(0.5, 1.05), ncol=2, framealpha=1.0, edgecolor='black')

        plt.tight_layout()
        filename = f'Figure_Stacking_Accuracy_{subj}_{hand}.png'
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        print(f"輸出成功: {filename}")
        plt.close()

    # ------------------------------------------
    # 圖表 2：Movement Economy
    # ------------------------------------------
    for subj in subject_keys:
        df_sess = subjects_data[subj]
        if df_sess.empty:
            continue

        fig, ax = plt.subplots(figsize=(6, 5), dpi=300)

        # 回歸線
        sns.regplot(x='Order', y='Hand_Area', data=df_sess, ax=ax,
                    scatter=True, color='#1f77b4', ci=95,
                    scatter_kws={'s': 60, 'zorder': 3},
                    line_kws={'linestyle': '--', 'label': 'Convergence Trend', 'color': 'gray'},
                    label='Hand Movement Area')

        # 折線圖
        valid_data = df_sess.dropna(subset=['Hand_Area'])
        ax.plot(valid_data['Order'], valid_data['Hand_Area'], color='#1f77b4', linewidth=2, zorder=2)

        ax.set_ylabel('Movement Area (m²)', fontweight='bold')
        max_order = df_sess['Order'].max()
        ax.set_xlim(0.5, max_order + 0.5)
        ax.set_ylim(y_min_area, y_max_area)
        ax.grid(True, alpha=0.3)
        ax.set_xlabel('Session Number', fontweight='bold')
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))

        ax.text(0.02, 0.95, f"Participant {subj}",
                transform=ax.transAxes, fontsize=13, fontweight='bold',
                va='top', ha='left', bbox=dict(facecolor='white', edgecolor='none', alpha=0.85))

        handles, lbls = ax.get_legend_handles_labels()
        by_label = dict(zip(lbls, handles))
        ax.legend(by_label.values(), by_label.keys(), loc='lower center',
                  bbox_to_anchor=(0.5, 1.05), ncol=2, framealpha=1.0, edgecolor='black')

        plt.tight_layout()
        filename = f'Figure_Movement_Economy_{subj}_{hand}.png'
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        print(f"輸出成功: {filename}")
        plt.close()

# ==========================================
# 4. 執行區塊
# ==========================================
file_mapping = {
    'A001': 'A001_data_train4.csv',
    'A002': 'A002_data_train4.csv',
    'A003': 'A003_data_train4.csv'
}

print("="*50)
print("正在處理已清洗的資料並產出 6 張 MDPI 期刊級圖檔")
print("="*50)

processed_subjects_data = {}
target_hand = '左'

for paper_id, csv_file in file_mapping.items():
    if os.path.exists(csv_file):
        processed_df = process_cleaned_data(csv_file)
        if processed_df is not None and not processed_df.empty:
            processed_subjects_data[paper_id] = processed_df
        else:
            print(f"{paper_id} 無有效資料")
    else:
        print(f"找不到檔案：{csv_file}")

if len(processed_subjects_data) > 0:
    plot_individual_figures(processed_subjects_data, hand=target_hand)
    print("\n所有獨立圖表已匯出完畢，可直接插入 Word 進行排版！")
else:
    print("\n沒有足夠的資料可以繪圖。")